### ISSUE TITLE
Working on Merge Sort

### ISSUE THREAD

**Issue by TravorLZH** [ParadoxZero/libgeneric#10]
I heard that you are going to add algorithms to this repository by reading your updated README.md, I am gonna help implement Merge Sort, the header files will be in directory `include/algorithm` while the source directory is in `src/algorithm`

**Comment by ParadoxZero** [comment]
Ensure it does not tie to a single data type.

Implement a key/comparator to be passed along the function s.t. any kind of data can be sorted.

If confused, I will be updating the BST to such an interface.

**Comment by TravorLZH** [comment]
To make it sort different data, I will provide a functional pointer as an input parameter that determines whether the value is **lesser** or **greater**

**Comment by ParadoxZero** [comment]
Yes, correct. 

E.g. 
```c
int comp(int a, int b){
    return a > b;
}
```

Generic one will be:
```c
int comp(void *a, void *b) {
    int a1 = *(int*)a;
    int b1 = *(int*)b;
    return a1>b1;
}
```

**Comment by TravorLZH** [comment]
Well, I am using this one

```c
int compare(void *a,void *b)
{
        int x=*(int*)a;
        int y=*(int*)b;
        return x-y;
}
```
So if x is less than y, the value will be negative. If x is greater, the value will be positive. If equal, the value will be zero. This is how `memcmp` and `strcmp` are implemented

**Comment by ParadoxZero** [comment]
The method I mentioned avoids an additional condition checking.

```c

if ( cmp(a,b) > 0) // Using the ret a-b

if (cmp(a,b)) // using ret a>b
```

The reason strcmp and memcmp use the abovementioned comparison is that they require 3 tier information about the comparison. However, for sorting, you only need to know if it's larger or smaller.

**Comment by TravorLZH** [comment]
My purpose of using this kind of condition checking because it does not only help sorting algorithm, but also other generic uses. So I should put it in `generic.h` instead

**Comment by ParadoxZero** [comment]
I guess benefits outweigh the problem. Go with the one you mentioned.
