### ISSUE TITLE
Vector Stack is already implemented

### ISSUE THREAD

**Issue by TravorLZH** [ParadoxZero/libgeneric#13]
I have implemented vector like `std::vector` which has LIFO ability like a stack, so why would you not tick on `Vector Stack`

**Comment by ParadoxZero** [comment]
Because in essence, it is still a `vector`. And not a stack.

**Comment by TravorLZH** [comment]
So we need a wrapper like `queue`

**Comment by ParadoxZero** [comment]
I am thinking, is wrapper really needed? maybe eliminate stack and queue. If a user wants they can just use the containers as needed.  Like how python does it.

**Comment by TravorLZH** [comment]
Why don't we use macros to wrap `vector` instead of functions, so it reduces the size of source. There will be no need of queue source file and no need of `queue.h` if we use something like the following:
```c
#ifndef DATA_STRUCTURE_VECTOR_H
#define DATA_STRUCTURE_VECTOR_H

extern void gVectorCreate(gVector *vector,size_t sz);
/* Other Vector Functions */
#ifdef ENABLE_VQUEUE
#define gVQueueCreate(q,sz) gVectorCreate(q,sz)
#define gVQueueFunction(q,arg) gVectorFunction(q,arg)
#endif
#endif
```

**Comment by ParadoxZero** [comment]
That's a nice idea. 

That way, we can allow the programmer to select the underlying container.

**Comment by TravorLZH** [comment]
Could you please tick on `Merge Sort` of your README

**Comment by ParadoxZero** [comment]
I thought you already did that in #15

Don't worry, will do that in next push.

**Comment by TravorLZH** [comment]
I will do the work of wrapping

**Comment by TravorLZH** [comment]
Is it ok if I change `VQueue` to `Queue`

**Comment by ParadoxZero** [comment]
> I'm gonna change it if no reply in 10 minutes

This is not how collaboration happens.

**Comment by ParadoxZero** [comment]
Due to inactivity closing it.
