### ISSUE TITLE
Implement one data structure that combines the features

### ISSUE THREAD

**Issue by TravorLZH** [ParadoxZero/libgeneric#20]
Recently, I found a template called deque, which is a vector that supports push and pop to the **front**. We just need to add features to that deque, so we can create **ONE** data structure that supports as many generic operations.

**Comment by ParadoxZero** [comment]
Double ended queue you mean?

I am thinking about a list of vectors.

**Comment by TravorLZH** [comment]
I think deque is terrific enough. We can also wrap functions from **utils** for this structure. The need of converting structure will be lesser.

**Comment by ParadoxZero** [comment]
Dequeue is simply a double-ended queue.

I am talking about the implementation.

**Comment by TravorLZH** [comment]
I can do it

**Comment by TravorLZH** [comment]
pop front = delete the 1st element. The deleted element is copied to another location
