### ISSUE TITLE
Documentation generation

### ISSUE THREAD

**Issue by TravorLZH** [ParadoxZero/libgeneric#9]
I really wonder why do you deny using doxygen documentation generator and cloud integration in your project. you should let others know how to use it if you want more people to contribute.

**Comment by ParadoxZero** [comment]
I am not denying it. I am just holding onto docs right now because there is no overarching design for the project yet.

As for CI, I just didn't want to use travisCI... they use very old ubuntu images that becomes a major source of headache as you move ahead.
